### ISSUE TITLE
Graphics Messed Up and Crashes

### ISSUE THREAD

**Issue by ParallelProductions** [cjbell630/FNaF_Advance#1]
Testing this on 2 different emulators, proved the same result. After the help wanted screen, the screen gets all scrambled and becomes unresponsive.

**Comment by cjbell630** [comment]
Sorry I didn't see the notification until now... just fixed it, thanks! Apparently the help wanted tiles were overwriting some important data for the office tiles, still not entirely sure what the data was though...

And as for the unresponsiveness... I still need to list the controls somewhere, that's on me lol

Thanks for checking this out though! I started on this a year ago and got burnt out after a week, but I'm hoping to finish it up very soon!
